/* tslint:disable */
/* eslint-disable */
/**
 * Webconsole Backend API
 * free5GC webconsole backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ANInformation {
    'IPAddress': string;
    'TEID': number;
}
export interface AccessAndMobilitySubscriptionData {
    'gpsis'?: Array<string>;
    'subscribedUeAmbr'?: SubscribedUeAmbr;
    'nssai'?: DefaultSingleNssais;
}
export interface AmPolicyData {
    'subscCats'?: Array<string>;
}
export interface Arp {
    'priorityLevel': number;
    'preemptCap': string;
    'preemptVuln': string;
}
export interface AuthenticationSubscription {
    'authenticationMethod': string;
    'permanentKey': PermanentKey;
    'sequenceNumber': string;
    'authenticationManagementField'?: string;
    'milenage'?: Milenage;
    'opc'?: Opc;
}
export interface ChargingData {
    'snssai'?: string;
    'dnn': string;
    'qosRef'?: number;
    'filter': string;
    'chargingMethod'?: string;
    'quota'?: string;
    'unitCost'?: string;
    'ueId'?: string;
}
export interface DefaultSingleNssais {
    'defaultSingleNssais': Array<Nssai>;
    'singleNssais'?: Array<Nssai>;
}
export interface Dnn {
    'dnn': string;
}
export interface DnnConfiguration {
    'pduSessionTypes': PduSessionTypes;
    'sscModes': SscModes;
    '5gQosProfile'?: Model5gQosProfile;
    'sessionAmbr'?: SessionAmbr;
    'staticIpAddress'?: Array<IpAddress>;
    'upSecurity'?: UpSecurity;
}
export interface FlowChargingRecord {
    'Supi': string;
    'Snssai': string;
    'Dnn': string;
    'Filter': string;
    'QuotaLeft': string;
    'Usage': string;
    'TotalVol': string;
    'UlVol': string;
    'DlVol': string;
}
export interface FlowRules {
    'filter'?: string;
    'precedence'?: number;
    'snssai'?: string;
    'dnn'?: string;
    'qosRef'?: number;
}
export interface IpAddress {
    'ipv4Addr'?: string;
    'ipv6Addr'?: string;
    'ipv6Prefix'?: string;
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'access_token'?: string;
    'refresh_token'?: string;
    'token_type'?: string;
    'expires_in'?: number;
}
export interface Meta {
    'next'?: string;
    'prev'?: string;
    'limit'?: number;
    'total'?: number;
}
export interface Milenage {
    'op'?: MilenageOp;
}
export interface MilenageOp {
    'opValue': string;
    'encryptionKey': number;
    'encryptionAlgorithm': number;
}
export interface Model5gQosProfile {
    '5qi': number;
    'arp': Arp;
    'priorityLevel'?: number;
}
export interface Nssai {
    'sst': number;
    'sd'?: string;
}
export interface Opc {
    'opcValue': string;
    'encryptionKey': number;
    'encryptionAlgorithm': number;
}
export interface PduSession {
    'Dnn': string;
    'PduSessionId': string;
    'Sd': string;
    'SmContextRef': string;
    'Sst': string;
}
export interface PduSessionInfo {
    'AnType': string;
    'Dnn': string;
    'LocalSEID'?: string;
    'PDUAddress': string;
    'PDUSessionID': string;
    'RemoteSEID'?: string;
    'Sd': string;
    'SessionRule': SessionRule;
    'Sst': string;
    'Supi': string;
    'Tunnel': Tunnel;
    'UpCnxState': string;
}
export interface PduSessionTypes {
    'defaultSessionType': string;
    'allowedSessionTypes'?: Array<string>;
}
export interface PermanentKey {
    'permanentKeyValue': string;
    'encryptionKey': number;
    'encryptionAlgorithm': number;
}
export interface Profile {
    'profileName': string;
    'AccessAndMobilitySubscriptionData': AccessAndMobilitySubscriptionData;
    'SessionManagementSubscriptionData': Array<SessionManagementSubscriptionData>;
    'SmfSelectionSubscriptionData': SmfSelectionSubscriptionData;
    'AmPolicyData': AmPolicyData;
    'SmPolicyData': SmPolicyData;
    'FlowRules': Array<FlowRules>;
    'QosFlows': Array<QosFlows>;
    'ChargingDatas': Array<ChargingData>;
}
export interface ProfileListIE {
    'profileName'?: string;
    'gpsi'?: string;
}
export interface QosFlows {
    'snssai': string;
    'dnn': string;
    'qosRef': number;
    '5qi': number;
    'mbrUL'?: string;
    'mbrDL'?: string;
    'gbrUL'?: string;
    'gbrDL'?: string;
}
export interface SessionAmbr {
    'uplink': string;
    'downlink': string;
}
export interface SessionManagementSubscriptionData {
    'singleNssai': Nssai;
    'dnnConfigurations'?: { [key: string]: DnnConfiguration; };
}
export interface SessionRule {
    'sessRuleId': string;
}
export interface SmPolicyData {
    'smPolicySnssaiData': { [key: string]: SmPolicySnssai; };
}
export interface SmPolicySnssai {
    'snssai': Nssai;
    'smPolicyDnnData'?: { [key: string]: Dnn; };
}
export interface SmfSelectionSubscriptionData {
    'subscribedSnssaiInfos'?: { [key: string]: SubscribedSnssaiInfo; };
}
export interface SscModes {
    'defaultSscMode': string;
    'allowedSscModes'?: Array<string>;
}
export interface SubscribedSnssaiInfo {
    'dnnInfos': Array<Dnn>;
}
export interface SubscribedUeAmbr {
    'uplink': string;
    'downlink': string;
}
export interface Subscriber {
    'plmnID': string;
    'ueId': string;
    'gpsi': string;
}
export interface Subscription {
    'userNumber'?: number;
    'plmnID': string;
    'ueId': string;
    'AuthenticationSubscription': AuthenticationSubscription;
    'AccessAndMobilitySubscriptionData': AccessAndMobilitySubscriptionData;
    'SessionManagementSubscriptionData': Array<SessionManagementSubscriptionData>;
    'SmfSelectionSubscriptionData': SmfSelectionSubscriptionData;
    'AmPolicyData': AmPolicyData;
    'SmPolicyData': SmPolicyData;
    'FlowRules': Array<FlowRules>;
    'QosFlows': Array<QosFlows>;
    'ChargingDatas': Array<ChargingData>;
}
export interface Tenant {
    'tenantId'?: string;
    'tenantName': string;
}
export interface Tunnel {
    'ANInformation': ANInformation;
    /**
     * github.com/free5gc/smf/internal/context/datapath.go:DataPathPool
     */
    'DataPathPool': any;
    /**
     * github.com/free5gc/util/idgenerator/idgenerator.go:IDGenerator
     */
    'PathIDGenerator': any;
}
export interface UeContext {
    'AccessType': string;
    'CmState': string;
    'Guti': string;
    'Mcc': string;
    'Mnc': string;
    'PduSessions': Array<PduSession>;
    'Supi': string;
    'Tac': string;
}
export interface UpSecurity {
    'upIntegr': string;
    'upConfid': string;
}
export interface User {
    'userId'?: string;
    'tenantId'?: string;
    'email': string;
    'encryptedPassword': string;
}

/**
 * WebconsoleApi - axios parameter creator
 */
export const WebconsoleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns an array of profile.
         * @summary Get all profiles
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileGet: async (limit?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete multiple subscribers
         * @param {Array<Subscriber>} subscriber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMultipleSubscribers: async (subscriber: Array<Subscriber>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'subscriber' is not null or undefined
            assertParamExists('deleteMultipleSubscribers', 'subscriber', subscriber)
            const localVarPath = `/api/subscriber`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscriber, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscriberByID: async (ueId: string, servingPlmnId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ueId' is not null or undefined
            assertParamExists('deleteSubscriberByID', 'ueId', ueId)
            // verify required parameter 'servingPlmnId' is not null or undefined
            assertParamExists('deleteSubscriberByID', 'servingPlmnId', servingPlmnId)
            const localVarPath = `/api/subscriber/{ueId}/{servingPlmnId}`
                .replace('{ueId}', encodeURIComponent(String(ueId)))
                .replace('{servingPlmnId}', encodeURIComponent(String(servingPlmnId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriberByID: async (ueId: string, servingPlmnId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ueId' is not null or undefined
            assertParamExists('getSubscriberByID', 'ueId', ueId)
            // verify required parameter 'servingPlmnId' is not null or undefined
            assertParamExists('getSubscriberByID', 'servingPlmnId', servingPlmnId)
            const localVarPath = `/api/subscriber/{ueId}/{servingPlmnId}`
                .replace('{ueId}', encodeURIComponent(String(ueId)))
                .replace('{servingPlmnId}', encodeURIComponent(String(servingPlmnId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns an array of subscriber.
         * @summary Get all subscribers
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscribers: async (limit?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/subscriber`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Partially update a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSubscriberByID: async (ueId: string, servingPlmnId: string, subscription: Subscription, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ueId' is not null or undefined
            assertParamExists('patchSubscriberByID', 'ueId', ueId)
            // verify required parameter 'servingPlmnId' is not null or undefined
            assertParamExists('patchSubscriberByID', 'servingPlmnId', servingPlmnId)
            // verify required parameter 'subscription' is not null or undefined
            assertParamExists('patchSubscriberByID', 'subscription', subscription)
            const localVarPath = `/api/subscriber/{ueId}/{servingPlmnId}`
                .replace('{ueId}', encodeURIComponent(String(ueId)))
                .replace('{servingPlmnId}', encodeURIComponent(String(servingPlmnId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscription, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSubscriberByID: async (ueId: string, servingPlmnId: string, subscription: Subscription, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ueId' is not null or undefined
            assertParamExists('postSubscriberByID', 'ueId', ueId)
            // verify required parameter 'servingPlmnId' is not null or undefined
            assertParamExists('postSubscriberByID', 'servingPlmnId', servingPlmnId)
            // verify required parameter 'subscription' is not null or undefined
            assertParamExists('postSubscriberByID', 'subscription', subscription)
            const localVarPath = `/api/subscriber/{ueId}/{servingPlmnId}`
                .replace('{ueId}', encodeURIComponent(String(ueId)))
                .replace('{servingPlmnId}', encodeURIComponent(String(servingPlmnId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscription, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Replace a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putSubscriberByID: async (ueId: string, servingPlmnId: string, subscription: Subscription, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ueId' is not null or undefined
            assertParamExists('putSubscriberByID', 'ueId', ueId)
            // verify required parameter 'servingPlmnId' is not null or undefined
            assertParamExists('putSubscriberByID', 'servingPlmnId', servingPlmnId)
            // verify required parameter 'subscription' is not null or undefined
            assertParamExists('putSubscriberByID', 'subscription', subscription)
            const localVarPath = `/api/subscriber/{ueId}/{servingPlmnId}`
                .replace('{ueId}', encodeURIComponent(String(ueId)))
                .replace('{servingPlmnId}', encodeURIComponent(String(servingPlmnId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscription, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebconsoleApi - functional programming interface
 */
export const WebconsoleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebconsoleApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns an array of profile.
         * @summary Get all profiles
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProfileGet(limit?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProfileListIE>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiProfileGet(limit, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.apiProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete multiple subscribers
         * @param {Array<Subscriber>} subscriber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMultipleSubscribers(subscriber: Array<Subscriber>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMultipleSubscribers(subscriber, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.deleteMultipleSubscribers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubscriberByID(ueId, servingPlmnId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.deleteSubscriberByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriberByID(ueId, servingPlmnId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.getSubscriberByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns an array of subscriber.
         * @summary Get all subscribers
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscribers(limit?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Subscriber>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscribers(limit, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.getSubscribers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Partially update a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchSubscriberByID(ueId, servingPlmnId, subscription, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.patchSubscriberByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSubscriberByID(ueId, servingPlmnId, subscription, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.postSubscriberByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Replace a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putSubscriberByID(ueId, servingPlmnId, subscription, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebconsoleApi.putSubscriberByID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WebconsoleApi - factory interface
 */
export const WebconsoleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebconsoleApiFp(configuration)
    return {
        /**
         * Returns an array of profile.
         * @summary Get all profiles
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProfileGet(limit?: number, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProfileListIE>> {
            return localVarFp.apiProfileGet(limit, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete multiple subscribers
         * @param {Array<Subscriber>} subscriber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMultipleSubscribers(subscriber: Array<Subscriber>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMultipleSubscribers(subscriber, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSubscriberByID(ueId, servingPlmnId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.getSubscriberByID(ueId, servingPlmnId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns an array of subscriber.
         * @summary Get all subscribers
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscribers(limit?: number, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Subscriber>> {
            return localVarFp.getSubscribers(limit, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Partially update a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.patchSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Replace a subscriber
         * @param {string} ueId 
         * @param {string} servingPlmnId 
         * @param {Subscription} subscription 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.putSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebconsoleApi - object-oriented interface
 */
export class WebconsoleApi extends BaseAPI {
    /**
     * Returns an array of profile.
     * @summary Get all profiles
     * @param {number} [limit] 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiProfileGet(limit?: number, page?: number, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).apiProfileGet(limit, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete multiple subscribers
     * @param {Array<Subscriber>} subscriber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteMultipleSubscribers(subscriber: Array<Subscriber>, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).deleteMultipleSubscribers(subscriber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a subscriber
     * @param {string} ueId 
     * @param {string} servingPlmnId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).deleteSubscriberByID(ueId, servingPlmnId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one subscriber
     * @param {string} ueId 
     * @param {string} servingPlmnId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubscriberByID(ueId: string, servingPlmnId: string, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).getSubscriberByID(ueId, servingPlmnId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns an array of subscriber.
     * @summary Get all subscribers
     * @param {number} [limit] 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubscribers(limit?: number, page?: number, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).getSubscribers(limit, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Partially update a subscriber
     * @param {string} ueId 
     * @param {string} servingPlmnId 
     * @param {Subscription} subscription 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public patchSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).patchSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a subscriber
     * @param {string} ueId 
     * @param {string} servingPlmnId 
     * @param {Subscription} subscription 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public postSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).postSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Replace a subscriber
     * @param {string} ueId 
     * @param {string} servingPlmnId 
     * @param {Subscription} subscription 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public putSubscriberByID(ueId: string, servingPlmnId: string, subscription: Subscription, options?: RawAxiosRequestConfig) {
        return WebconsoleApiFp(this.configuration).putSubscriberByID(ueId, servingPlmnId, subscription, options).then((request) => request(this.axios, this.basePath));
    }
}



