backend:
  username: "admin"
  password: "frulab"

  port: 8888

  jwt:
    secret: "fru-lab"
    expiresIn: 1h

  db:
    type: "bbolt"
    path: "/tmp/frulab.db"

  deploy:
    workDir: "/tmp/frulab-deploy"

  frontendFilePath: "build/frontend"

logger:
  level: "info"