/* tslint:disable */
/* eslint-disable */
/**
 * full-stack-framework API
 * Automatically generated OpenAPI spec from Postman collection \"full-stack-framework\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface DeployLogsResponse {
    'target': string;
    'lines': Array<string>;
}
export interface DeployStatusResponse {
    'target': string;
    'status': string;
    'services'?: Array<ServiceStatus>;
    'lastDeployed'?: string;
}
export interface DeployUeListResponse {
    'instances'?: Array<DeployUeStatusResponse>;
}
export interface DeployUeLogsResponse {
    'instance': string;
    'lines': Array<string>;
}
export interface DeployUeRequest {
    'mcc': string;
    'mnc': string;
    'msin': string;
    'permanentKey': string;
    'opValue': string;
    'amf': string;
    'sqn': string;
    'dnn': string;
    'sst': string;
    'sd'?: string;
}
export interface DeployUeStatusResponse {
    'instance': string;
    'status': string;
    'services'?: Array<ServiceStatus>;
    'lastDeployed'?: string;
}
export interface ImageInfo {
    'key': string;
    'name': string;
    'image': string;
    'group': string;
    /**
     * Whether the image is currently present in the local docker image cache.
     */
    'present': boolean;
    /**
     * Image size in bytes. Omitted when not present locally.
     */
    'size'?: number;
    /**
     * When the locally cached image was built. Omitted when not present locally.
     */
    'createdAt'?: string;
}
export interface ImageListResponse {
    'images'?: Array<ImageInfo>;
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'message': string;
    'token': string;
}
export interface MessageResponse {
    'message'?: string;
}
export interface ServiceStatus {
    'name': string;
    'status': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fails with 409 if gNB is still running - gNB must be stopped first.
         * @summary Stop free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcDown: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/free5gc`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get free5GC container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcLogs: async (service?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/free5gc/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (service !== undefined) {
                localVarQueryParameter['service'] = service;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get free5GC deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/free5gc/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deploy free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcUp: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/free5gc`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fails with 409 if any UE instance is still running - all UE instances must be stopped first.
         * @summary Stop gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbDown: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/gnb`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get gNB container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbLogs: async (service?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/gnb/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (service !== undefined) {
                localVarQueryParameter['service'] = service;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get gNB deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/gnb/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fails with 409 if the core network isn\'t running yet - deploy free5gc first.
         * @summary Deploy gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbUp: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/gnb`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stop a UE instance
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeDown: async (instance: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('deployUeDown', 'instance', instance)
            const localVarPath = `/api/deploy/ue/{instance}`
                .replace('{instance}', encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all deployed UE instances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/deploy/ue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a UE instance\'s container logs
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeLogs: async (instance: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('deployUeLogs', 'instance', instance)
            const localVarPath = `/api/deploy/ue/{instance}/logs`
                .replace('{instance}', encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a UE instance\'s deploy status
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeStatus: async (instance: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('deployUeStatus', 'instance', instance)
            const localVarPath = `/api/deploy/ue/{instance}/status`
                .replace('{instance}', encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fails with 409 if gNB isn\'t running yet - deploy gNB first.
         * @summary Deploy a UE instance for one subscriber
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {DeployUeRequest} deployUeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeUp: async (instance: string, deployUeRequest: DeployUeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('deployUeUp', 'instance', instance)
            // verify required parameter 'deployUeRequest' is not null or undefined
            assertParamExists('deployUeUp', 'deployUeRequest', deployUeRequest)
            const localVarPath = `/api/deploy/ue/{instance}`
                .replace('{instance}', encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deployUeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reports every image pinned by the compose templates (free5gc\'s NFs, mongo, and free-ran-ue), and whether each is currently present in the local docker image cache.
         * @summary List the images this app deploys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Re-pulls the image\'s pinned tag from its registry.
         * @summary Pull an image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imagePull: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('imagePull', 'key', key)
            const localVarPath = `/api/images/{key}/pull`
                .replace('{key}', encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes the image from the local docker image cache, forcing the next deploy to pull it fresh. Fails if a container is currently using it.
         * @summary Clear a locally cached image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageRemove: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('imageRemove', 'key', key)
            const localVarPath = `/api/images/{key}`
                .replace('{key}', encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Fails with 409 if gNB is still running - gNB must be stopped first.
         * @summary Stop free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployFree5gcDown(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployFree5gcDown(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployFree5gcDown']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get free5GC container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployFree5gcLogs(service?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployLogsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployFree5gcLogs(service, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployFree5gcLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get free5GC deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployFree5gcStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployFree5gcStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployFree5gcStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deploy free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployFree5gcUp(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployFree5gcUp(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployFree5gcUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fails with 409 if any UE instance is still running - all UE instances must be stopped first.
         * @summary Stop gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployGnbDown(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployGnbDown(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployGnbDown']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get gNB container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployGnbLogs(service?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployLogsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployGnbLogs(service, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployGnbLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get gNB deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployGnbStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployGnbStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployGnbStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fails with 409 if the core network isn\'t running yet - deploy free5gc first.
         * @summary Deploy gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployGnbUp(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployGnbUp(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployGnbUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Stop a UE instance
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployUeDown(instance: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployUeDown(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployUeDown']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all deployed UE instances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployUeList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployUeListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployUeList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployUeList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a UE instance\'s container logs
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployUeLogs(instance: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployUeLogsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployUeLogs(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployUeLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a UE instance\'s deploy status
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployUeStatus(instance: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeployUeStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployUeStatus(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployUeStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fails with 409 if gNB isn\'t running yet - deploy gNB first.
         * @summary Deploy a UE instance for one subscriber
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {DeployUeRequest} deployUeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deployUeUp(instance: string, deployUeRequest: DeployUeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deployUeUp(instance, deployUeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deployUeUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reports every image pinned by the compose templates (free5gc\'s NFs, mongo, and free-ran-ue), and whether each is currently present in the local docker image cache.
         * @summary List the images this app deploys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imageList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImageListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imageList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.imageList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Re-pulls the image\'s pinned tag from its registry.
         * @summary Pull an image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imagePull(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imagePull(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.imagePull']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes the image from the local docker image cache, forcing the next deploy to pull it fresh. Fails if a container is currently using it.
         * @summary Clear a locally cached image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imageRemove(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imageRemove(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.imageRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Fails with 409 if gNB is still running - gNB must be stopped first.
         * @summary Stop free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcDown(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployFree5gcDown(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get free5GC container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcLogs(service?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeployLogsResponse> {
            return localVarFp.deployFree5gcLogs(service, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get free5GC deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcStatus(options?: RawAxiosRequestConfig): AxiosPromise<DeployStatusResponse> {
            return localVarFp.deployFree5gcStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deploy free5GC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployFree5gcUp(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployFree5gcUp(options).then((request) => request(axios, basePath));
        },
        /**
         * Fails with 409 if any UE instance is still running - all UE instances must be stopped first.
         * @summary Stop gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbDown(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployGnbDown(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get gNB container logs
         * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbLogs(service?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeployLogsResponse> {
            return localVarFp.deployGnbLogs(service, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get gNB deploy status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbStatus(options?: RawAxiosRequestConfig): AxiosPromise<DeployStatusResponse> {
            return localVarFp.deployGnbStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * Fails with 409 if the core network isn\'t running yet - deploy free5gc first.
         * @summary Deploy gNB
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployGnbUp(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployGnbUp(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stop a UE instance
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeDown(instance: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployUeDown(instance, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all deployed UE instances
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeList(options?: RawAxiosRequestConfig): AxiosPromise<DeployUeListResponse> {
            return localVarFp.deployUeList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a UE instance\'s container logs
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeLogs(instance: string, options?: RawAxiosRequestConfig): AxiosPromise<DeployUeLogsResponse> {
            return localVarFp.deployUeLogs(instance, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a UE instance\'s deploy status
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeStatus(instance: string, options?: RawAxiosRequestConfig): AxiosPromise<DeployUeStatusResponse> {
            return localVarFp.deployUeStatus(instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Fails with 409 if gNB isn\'t running yet - deploy gNB first.
         * @summary Deploy a UE instance for one subscriber
         * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
         * @param {DeployUeRequest} deployUeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deployUeUp(instance: string, deployUeRequest: DeployUeRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deployUeUp(instance, deployUeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Reports every image pinned by the compose templates (free5gc\'s NFs, mongo, and free-ran-ue), and whether each is currently present in the local docker image cache.
         * @summary List the images this app deploys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageList(options?: RawAxiosRequestConfig): AxiosPromise<ImageListResponse> {
            return localVarFp.imageList(options).then((request) => request(axios, basePath));
        },
        /**
         * Re-pulls the image\'s pinned tag from its registry.
         * @summary Pull an image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imagePull(key: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.imagePull(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes the image from the local docker image cache, forcing the next deploy to pull it fresh. Fails if a container is currently using it.
         * @summary Clear a locally cached image
         * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageRemove(key: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.imageRemove(key, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * Fails with 409 if gNB is still running - gNB must be stopped first.
     * @summary Stop free5GC
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployFree5gcDown(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployFree5gcDown(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get free5GC container logs
     * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployFree5gcLogs(service?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployFree5gcLogs(service, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get free5GC deploy status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployFree5gcStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployFree5gcStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deploy free5GC
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployFree5gcUp(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployFree5gcUp(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fails with 409 if any UE instance is still running - all UE instances must be stopped first.
     * @summary Stop gNB
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployGnbDown(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployGnbDown(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get gNB container logs
     * @param {string} [service] Filter logs down to one compose service (NF), e.g. \&quot;amf\&quot;. Omit for every service in the project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployGnbLogs(service?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployGnbLogs(service, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get gNB deploy status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployGnbStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployGnbStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fails with 409 if the core network isn\'t running yet - deploy free5gc first.
     * @summary Deploy gNB
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployGnbUp(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployGnbUp(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Stop a UE instance
     * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployUeDown(instance: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployUeDown(instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all deployed UE instances
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployUeList(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployUeList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a UE instance\'s container logs
     * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployUeLogs(instance: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployUeLogs(instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a UE instance\'s deploy status
     * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployUeStatus(instance: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployUeStatus(instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fails with 409 if gNB isn\'t running yet - deploy gNB first.
     * @summary Deploy a UE instance for one subscriber
     * @param {string} instance The subscriber\&#39;s UE ID (IMSI), used as the UE instance identifier.
     * @param {DeployUeRequest} deployUeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deployUeUp(instance: string, deployUeRequest: DeployUeRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deployUeUp(instance, deployUeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Reports every image pinned by the compose templates (free5gc\'s NFs, mongo, and free-ran-ue), and whether each is currently present in the local docker image cache.
     * @summary List the images this app deploys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imageList(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).imageList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Re-pulls the image\'s pinned tag from its registry.
     * @summary Pull an image
     * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imagePull(key: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).imagePull(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes the image from the local docker image cache, forcing the next deploy to pull it fresh. Fails if a container is currently using it.
     * @summary Clear a locally cached image
     * @param {string} key The image\&#39;s stable route key, as returned by GET /api/images (e.g. \&quot;amf\&quot;, \&quot;mongo\&quot;, \&quot;free-ran-ue\&quot;).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imageRemove(key: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).imageRemove(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }
}



